# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('version_name', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tmc_alias', models.CharField(max_length=255)),
                ('file_mask', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ManyToManyField(to='dashboard.Feature', verbose_name='Features')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='featurematching',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Version'),
        ),
        migrations.AddField(
            model_name='automationresult',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Feature'),
        ),
        migrations.AddField(
            model_name='automationresult',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Version'),
        ),
    ]
